### ISSUE TITLE
Games / Flood

### ISSUE THREAD

**Issue by tgrajewski** [photonstorm/phaser3-examples#67] opened 2018-03-22 10:50 UTC
https://labs.phaser.io/view.html?src=src\games\flood\flood-fill.js

Sometimes during play monsters gets displaced after a click.

![screenshot_1](https://user-images.githubusercontent.com/4324821/37766404-22b7a57e-2dc7-11e8-850b-1e9c89e52654.png)

**Comment by Matthew-Herman** [comment] 2018-03-22 19:26
This is a duplicate of issue #22. I have been looking at this bug and it seems to be an issue with stopping the tween that plays once a user mouses over a monster icon.

On line 364 we have this function
```javascript
    onIconOut: function (pointer, gameObject)
    {
        console.log(this.monsterTween.targets[0].y);

        //this line causes monster.y to become 0 when cursor moves erratically 
        this.monsterTween.stop(0);

        console.log(this.monsterTween.targets[0].y);

        this.cursorTween = this.tweens.add({
            targets: this.cursor,
            alpha: 0,
            duration: 300
        });

        this.arrow.setFrame('arrow-white');
    },
```
It is certainly the behvaior of ``` this.monsterTween.stop(0);```, which causes the tween to stop but sometimes erroneously sets the y position of the monster icon to 0. I'm struggling to find out why this is because I don't know how stopping Tweens is implemented.

**Closed** 2018-03-22 19:45 UTC
